### ISSUE TITLE
Sync water-tracker data with Firebase

### ISSUE THREAD

**Issue by Ashutosh74554** [Ashutosh74554/ShapeUp#2]
Update the water tracker data whenever it is changed and upload it to Firebase to sync with it.

**Comment by Manas8260** [comment]
Can I work on this?

**Comment by Ashutosh74554** [comment]
> Can I work on this?

Yes. After completion, make a PR

**Comment by Ashutosh74554** [comment]
Merged your PR. Thank you for contributing
